# 实验一：Pytorch基本操作考察

In [6]:
import torch

## 1. 使用 𝐓𝐞𝐧𝐬𝐨𝐫 初始化一个 𝟏 × 𝟑 的矩阵 𝑴 和一个 𝟐 × 𝟏 的矩阵 𝑵，对两矩阵进行减法操作（要求实现三种不同的形式），给出结果并分析三种方式的不同（如果出现报错，分析报错的原因），同时需要指出在计算过程中发生了什么

In [7]:
M = torch.rand(1,3)
N = torch.rand(2,1)
print(M)
print(N)

tensor([[0.4745, 0.1138, 0.3812]])
tensor([[0.1164],
        [0.7796]])


In [8]:
# 减法形式一
diff1 = M - N
print(diff1)

tensor([[ 0.3581, -0.0025,  0.2648],
        [-0.3051, -0.6657, -0.3984]])


In [9]:
# 减法形式二
diff2 = torch.sub(M, N)
print(diff2)

tensor([[ 0.3581, -0.0025,  0.2648],
        [-0.3051, -0.6657, -0.3984]])


In [10]:
# 减法形式三
diff3 = M.sub_(N)
print(diff3)

RuntimeError: output with shape [1, 3] doesn't match the broadcast shape [2, 3]

## 2.
1) 利用 𝐓𝐞𝐧𝐬𝐨𝐫 创建两个大小分别 𝟑 × 𝟐 和 𝟒 × 𝟐 的随机数矩阵 𝑷 和 𝑸 ，要求服从均值为0，标准差0.01为的正态分布 
2) 对第二步得到的矩阵 𝑸 进行形状变换得到 𝑸 的转置 𝑸^𝑻 
3) 对上述得到的矩阵 𝑷 和矩阵 𝑸^𝑻 求乘积

In [11]:
P = torch.normal(0, 0.01, size=(3,2))
Q = torch.normal(0, 0.01, size=(4,2))
print(P)
print(Q)

tensor([[ 0.0036,  0.0050],
        [-0.0192,  0.0031],
        [ 0.0171,  0.0019]])
tensor([[-0.0060, -0.0013],
        [ 0.0018,  0.0209],
        [ 0.0044,  0.0025],
        [-0.0011, -0.0214]])


In [12]:
QT = torch.t(Q)
print(QT)

tensor([[-0.0060,  0.0018,  0.0044, -0.0011],
        [-0.0013,  0.0209,  0.0025, -0.0214]])


In [13]:
mm = torch.mm(P,QT)
print(torch.mm(P,QT))

tensor([[-2.8090e-05,  1.0999e-04,  2.8282e-05, -1.1004e-04],
        [ 1.1148e-04,  3.1094e-05, -7.7134e-05, -4.5545e-05],
        [-1.0526e-04,  7.0529e-05,  8.0329e-05, -6.0015e-05]])


## 3.给定公式 $𝑦_3 = 𝑦_1 + 𝑦_2 = 𝑥^2 + 𝑥^3$，且 𝑥 = 1。利用学习所得到的Tensor的相关知识，求$𝑦_3$对的梯度𝑥，即$𝑑𝑦_3/𝑑𝑥$ 。

In [26]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2
with torch.no_grad(): # 为什么要追踪
    y2 = x ** 3
y3 = y1 + y2
print(y3)
print(y3.grad_fn) # .grad_fn输出的是什么？
y3.backward() # 向后
print(x.grad) # 实际计算得到的梯度值

tensor(2., grad_fn=<AddBackward0>)
tensor(2.)
